create table public.user_metadata
(
    id          bigint generated by default as identity primary key,
    user_id     uuid references auth.users on delete cascade not null, -- uuid from auth.users
    field_name  text,
    field_value text,

    unique (user_id, field_name)
);
comment
on table public.user_metadata is 'Profile data for each user.';
comment
on column public.user_metadata.id is 'UUID for each metadata row.';
comment
on column public.user_metadata.user_id is 'References the internal supabase auth.users table.';
